<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SafeLock.Application\SafeLock.Application.csproj" />
    <ProjectReference Include="..\..\SafeLock.Infrastructure\SafeLock.Infrastructure.csproj" />
    <ProjectReference Include="..\..\SafeLock.Shared\SafeLock.Shared.csproj" />
  </ItemGroup>

</Project>
